version: "3.8"

services:
mysql: 
  image: mysql:latest
  container_name: mysql
  restart: always
  environment:
    MYSQL_ROOT_PASSWORD: 1234
    MYSQL_DATABASE: studentapp
  volumes:
    - mysql_data:/var/lib/mysql
    - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  ports:
    - "3306:3306"

  backend:
    build:
      context: ./BE
    container_name: tomcat-backend
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_PORT: 3306

  frontend:
    build:
      context: ./FE
    container_name: apache-frontend
    ports:
      - "80:80"

volumes:
  mysql_data:

