apiVersion: apps/v1
kind: Deployment 
metadata:
   name: my-deploy
   labels:
      app: deployment-app
spec:
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
        - name: deployment-container
          image: httpd
          