apiVersion: apps/v1
kind: Deployment 
metadata:
   name: my-deploy
   labels:
      app: deployment-app
spec:
  template:
    metadata:
      labels:
        app: deployment-app
    spec:
      containers:
        - name: deployment-container
          image: httpd
          ports:
           - containerPort: 80
          resource:
            limits:
              cpu: 15m
              memory: 100Mi
            requests:
              cpu: 10m 
              memory: 50Mi 
         

  replicas: 3
 
  selector:
    matchLabels:
      app: deployment-app
  strategy:
     type: RollingUpdate