apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              name: my-var # Name of the ConfigMap
              key: db_password
        - name: MYSQL_USER_NAME
          valueFrom:
            configMapKeyRef:
              name: my-var # Name of the ConfigMap
              key: user_name
        - name: DB_Name
          valueFrom:
            configMapKeyRef:
              name: my-var # Name of the ConfigMap
              key: database_name
