apiVersion: v1
kind: Pod
metadata:
  labels:
    app: mysql
  name: mysql
spec:
  containers:
    - name: mysql
      image: mysql
      ports:
        - name: mysql
          containerPort: 3306
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: Redhat
        - name: MYSQL_USER_NAME
          value: rajat
        - name: DB_Name
          value: studentapp

          # envpass to configmap

        - name:  MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: db_password
        - name:  MYSQL_USER_NAME
          valueFrom:
            configMapKeyRef:
              key: user_name
        - name:  MYSQL_ROOT_PASSWORD
          valueFrom:
            configMapKeyRef:
              key: db_password            